### PR TITLE
Koji: add section about locally reproducing image builds

### PR DESCRIPTION
**Pull request by thozza**
Add a section how can one reproduce image builds locally, using the files and information attached to each Koji build.

### CODE REVIEW

**Comment by supakeen** [comment]
Are the composes available for a limited timespan and if so should this be noted?

**Review by achilleas-k — APPROVED** [review]
LGTM

**Comment by achilleas-k** [comment]
> Are the composes available for a limited timespan and if so should this be noted?

I think they don't expire, but I might be wrong.  If they do, it's pretty long.

**Review by ochosi — APPROVED** [review]
<3

**Comment by thozza** [comment]
> Are the composes available for a limited timespan and if so should this be noted?

I would say that this heavily depends on the pipeline configuration, which is distribution-specific. I didn't include any note on that, because this docs is distribution-agnostic. But in reality, it may happen that the compose from which the image is already gone and thus one would not be able to rebuild the image using the attached manifest. But if this happens, the image build itself is probably not relevant any more (since images built as part of a compose are part of the compose itself).

**Pull request merged**
